icee:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: icee-sky
    username: root
    password: lxq2007A1
  jwt: # 设置jwt签名加密时使用的秘钥
      admin-secret-key: itcast
      # 设置jwt过期时间
      admin-ttl: 7200000
      # 设置前端传递过来的令牌名称
      admin-token-name: token


server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
      driver-class-name: ${icee.datasource.driver-class-name}
      url: jdbc:mysql://${icee.datasource.host}:${icee.datasource.port}/${icee.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#      url: jdbc:mysql://localhost:3306/icee-sky?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${icee.datasource.username}
      password: ${icee.datasource.password}
      #    需要在pom中引入druid依赖
      type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  #mapper配置文件
  mapper-locations: classpath:com/icee/mapper/*.xml
  type-aliases-package: com.icee.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
    #日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

# application.yml 配置示例
pagehelper:
  helper-dialect: mysql  # 这是关键配置！根据你的数据库调整
  reasonable: true       # 分页合理化，可选
  support-methods-arguments: true # 支持接口参数，可选