server:
  port: 8081
  address: 0.0.0.0   #允许外部访问

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
      driver-class-name: ${icee.datasource.driver-class-name}
      url: jdbc:mysql://${icee.datasource.host}:${icee.datasource.port}/${icee.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#      url: jdbc:mysql://localhost:3306/icee-sky?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${icee.datasource.username}
      password: ${icee.datasource.password}
      #    需要在pom中引入druid依赖
      type: ${icee.datasource.type}
  servlet:
    multipart:
      #      每次max
      max-file-size: 50MB
      #      每次连接max
      max-request-size: 200MB
  data:
    redis:
      host: ${icee.data.redis.host}
      port: ${icee.data.redis.port}
      password: ${icee.data.redis.password}
      database: ${icee.data.redis.database}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:com/icee/mapper/*.xml
  type-aliases-package: com.icee.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
    #日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

aliyun:
  oss:
    endpoint: ${icee.aliyun.oss.endpoint}
    bucket-name: ${icee.aliyun.oss.bucket-name}
    region: ${icee.aliyun.oss.region}


icee:
  jwt: # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 72000000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: itcast
    user-ttl: 72000000
    user-token-name: authentication
  WeChat:
    appid: ${icee.WeChat.appid}
    secret: ${icee.WeChat.secret}
  Baidu:
    AK: ${icee.Baidu.AK}
    shop: ${icee.Baidu.shop}
    URL: ${icee.Baidu.URL}
    lng: ${icee.Baidu.lng}
    lat: ${icee.Baidu.lat}